In [1]:
import pandas as pd
from pycaret.regression import *
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [3]:
flood_data = pd.read_csv('data/flood.csv')

In [12]:
numerical_features = ['year', 'rainfall','runoff']
categorical_features = ['month', 'region']

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    #('scaler', StandardScaler())
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_features),
        ('cat_transform', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features)
        ],
    remainder='passthrough'
)

In [ ]:
historic_data_processed = preprocessor.fit_transform(historic_data)
categorical_feature_names = preprocessor.named_transformers_['cat_transform'].get_feature_names_out(categorical_features)
all_feature_names = numerical_features + list(categorical_feature_names)
historic_df = pd.DataFrame(historic_data_processed, columns=all_feature_names)
historic_df.head()

,year,rainfall,runoff,month_April,month_Aug.,month_Dec.,month_Feb.,month_Jan.,month_July,month_June,month_March,month_May,month_Nov.,month_Oct.,month_Sept.,region_Kagera,region_Lake Victoria,region_Simiyu,region_Victoria Nile
0,2000.0,0.123000,816.334,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2000.0,0.966000,972.481,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,2000.0,0.096000,393.089,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,2000.0,3.092385,744.105,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,2000.0,1.415000,1041.783,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [4]:
flood_data.head()

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,Encroachments,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,3,8,6,6,4,4,6,2,3,2,...,10,7,4,2,3,4,3,2,6,0.450
1,8,4,5,7,7,9,1,5,5,4,...,9,2,6,2,1,1,9,1,3,0.475
2,3,10,4,1,7,5,4,7,4,9,...,7,4,4,8,6,1,8,3,6,0.515
3,4,4,2,7,3,4,1,4,6,4,...,4,2,6,6,8,8,6,6,10,0.520
4,3,7,5,2,5,8,5,2,7,5,...,7,6,5,3,3,4,4,3,4,0.475

In [5]:
s = setup(data=flood_data, target='FloodProbability', session_id=5)

In [6]:
best = compare_models(sort='MAE', exclude=['lightgbm'])
results = pull()
print(results.iloc[0])

Initiated  . . . . . . . . . . . . . . . . . .           11:00:34
Status     . . . . . . . . . . . . . . . . . .  Loading Estimator
Estimator  . . . . . . . . . . . . . . . . . .  Compiling Library

Model       Linear Regression
MAE                       0.0
MSE                       0.0
RMSE                      0.0
R2                        1.0
RMSLE                     0.0
MAPE                      0.0
TT (Sec)                0.319
Name: lr, dtype: object

In [ ]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [60]:
"""
    I'm just trying to see how well the predictions from the gbr model align with the projected runoffs.
    I'm not sure though if this is the best way to do it.
"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

#projected_data is the data that has been projected with runoffs
projected_data = pd.read_csv('data/combined_data/projected/projected_lakevic_data.csv')
# print(projected_data.describe())

#predictionData is the data that will be used to predict the runoffs and therefore does not include the runoff column.
predictionData = projected_data.drop(columns=['runoff'])
gbrPrediction = predict_model(best, data=predictionData)
gbrPrediction.rename(columns={'prediction_label': 'runoff'}, inplace=True)
comp_df = pd.merge(projected_data, gbrPrediction, on=['year', 'month', 'region'], suffixes=('_actual', '_pred'))
#print(gbrPrediction)
print(comp_df)
print("\nThe Mean Absolute Error : %d " %(mean_absolute_error(comp_df['runoff_actual'], comp_df['runoff_pred'])))  # MAE
print("The Mean Squared Error : %d " %(mean_squared_error(comp_df['runoff_actual'], comp_df['runoff_pred'])))  # MSE
print("The R2 Score : %f " %(r2_score(comp_df['runoff_actual'], comp_df['runoff_pred'])))  # R2

     year  month         region  rainfall_actual  runoff_actual  \
0    2026  April         Kagera            5.478       1381.322
1    2026  April  Lake Victoria           11.460        708.806
2    2026  April         Simiyu            4.534        708.806
3    2026  April  Victoria Nile              NaN       3611.252
4    2026   Aug.         Kagera            0.298         85.005
..    ...    ...            ...              ...            ...
475  2035   Oct.  Victoria Nile              NaN       3204.099
476  2035  Sept.         Kagera            3.839        250.111
477  2035  Sept.  Lake Victoria            3.825        183.906
478  2035  Sept.         Simiyu            9.079        183.906
479  2035  Sept.  Victoria Nile              NaN       1474.566

     rainfall_pred  runoff_pred
0            5.478   798.347180
1           11.460  1168.612164
2            4.534   831.522967
3              NaN  1837.428064
4            0.298    63.432866
..             ...          ...
475            NaN   817.170889
476          3.839   220.732624
477          3.825   117.288625
478          9.079    38.301618
479            NaN   817.170889

[480 rows x 7 columns]

The Mean Absolute Error : 386
The Mean Squared Error : 623553
The R2 Score : 0.217241