In [4]:
import pandas as pd

In [22]:
original_data = pd.read_csv('data/combined_data/lakevic_kagera_simiyu_victorianile_allregions.csv')
transformed_data = pd.read_csv('data/combined_data/lakevic_kagera_simiyu_victorianile_transformed.csv')

# Describe each dataset
#print("Original Data Description:")
#print(original_data.describe(include='all'))
print("\nTransformed Data Description:")
print(transformed_data.describe())

Transformed Data Description:
              year     rainfall       runoff
count  1696.000000  1272.000000  1696.000000
mean   2017.830189     3.186994   349.844495
std      10.204259     3.684587   753.661603
min    2000.000000     0.010000     0.000000
25%    2009.000000     0.407750     3.698750
50%    2018.000000     1.856000    43.084000
75%    2027.000000     4.658500   337.897000
max    2035.000000    22.771000  5601.258000

In [9]:
original_data.head(5)

   region data_type  year month  value
0  Kagera  rainfall  2000  Jan.    NaN
1  Kagera  rainfall  2001  Jan.  6.532
2  Kagera  rainfall  2002  Jan.  1.805
3  Kagera  rainfall  2003  Jan.  7.727
4  Kagera  rainfall  2004  Jan.  1.912

In [11]:
transformed_data.head(10)

   year month         region  rainfall    runoff
0  2000  Dec.         Kagera     0.123   816.334
1  2000  Dec.  Lake Victoria     0.966   972.481
2  2000  Dec.         Simiyu     0.096   393.089
3  2000  Dec.  Victoria Nile       NaN   744.105
4  2000  Nov.         Kagera     1.415  1041.783
5  2000  Nov.  Lake Victoria     9.887  2200.189
6  2000  Nov.         Simiyu     1.121   498.359
7  2000  Nov.  Victoria Nile       NaN  1598.860
8  2000  Oct.         Kagera     1.646  1564.320
9  2000  Oct.  Lake Victoria     3.035  1447.993

In [20]:
victoriaOriginal = original_data.loc[(original_data['region'] == 'Victoria Nile') & (original_data.data_type == 'runoff') & (original_data['year'] == '2000') & (original_data['month'] == 'Nov.')]
victoriaOriginal

             region data_type  year month    value
2532  Victoria Nile    runoff  2000  Nov.  1598.86

In [23]:
yearNullTest = transformed_data.loc[transformed_data.year.isnull()]
print("\nYear Null Test:")
print(yearNullTest)

Year Null Test:
Empty DataFrame
Columns: [year, month, region, rainfall, runoff]
Index: []

In [24]:
historicalData = pd.read_csv('data/combined_data/historical/historical_lakevic_data.csv')
projectedData = pd.read_csv('data/combined_data/projected/projected_lakevic_data.csv')

print(historicalData.describe())
print(projectedData.describe())

              year    rainfall       runoff
count  1216.000000  912.000000  1216.000000
mean   2012.828947    3.092385   308.279029
std       7.318077    3.553806   686.719391
min    2000.000000    0.010000     0.000000
25%    2006.750000    0.415500     2.794500
50%    2013.000000    1.835000    41.222000
75%    2019.000000    4.597250   294.049750
max    2025.000000   22.771000  5544.254000
              year    rainfall       runoff
count   480.000000  360.000000   480.000000
mean   2030.500000    3.426672   455.143675
std       2.875278    3.991976   893.461287
min    2026.000000    0.016000     0.000000
25%    2028.000000    0.399000     7.223000
50%    2030.500000    1.948000    51.034500
75%    2033.000000    4.942500   506.679000
max    2035.000000   22.497000  5601.258000